variables:
  NX_APP: "NX_APP"

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - nx run $NX_APP:build --outputPath=build

test:
  stage: build
  script:
    - nx run $NX_APP:test --outputPath=build

list:
  stage: build
  script:
    - nx run $NX_APP:lint --outputPath=build
    -
deploy-stage:
  stage: deploy
  script:
    - echo "Deploying to stage"
  environment:
    name: stage
    url: https://stage.example.com
    deployment_tier: staging

deploy-production:
  stage: deploy
  script:
    - echo "Deploying to production"
  environment:
    name: production
    url: https://prod.example.com
    deployment_tier: production
  only:
      - tags
